from django.urls import path

from . import views


urlpatterns = [
    path('', views.home_view, name='home'),
    path('404', views.handler404),
    path('500', views.handler_server_error),
    path('signup', views.signup_view, name='signup'),
    path('signup/confirm/<pk>/<token>', views.signup_confirm_email_view, name='signup_confirm_email'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('forgot-password', views.forgot_password_view, name='forgot_password'),
    path('reset-password/confirm/<pk>/<token>', views.reset_password_view, name='reset_password'),
    path('set_lang', views.set_lang_view, name='set_lang'),
    path('about', views.about_us_view, name='about_us'),
    path('contact', views.contact_us_view, name='contact_us'),
    path('account', views.organization_personal_account_view, name='organization_personal_account'),
    path('representative/signup/confirm/<pk>/<token>', views.signup_confirm_representative_view, name='signup_confirm_representative'),
    path('representative/add', views.add_university_representative_view, name='add_university_representative'),
    path('companies', views.list_companies_view, name='list_companies'),
    path('company/edit', views.company_edit_view, name='company_edit'),
    path('company/<int:pk>', views.company_detail_view, name='company_detail'),
    path('universities', views.list_universities_view, name='list_universities'),
    path('university/edit', views.university_edit_view, name='university_edit'),
    path('university/<int:pk>', views.university_detail_view, name='university_detail'),
    path('university/students', views.university_students_view, name='university_students'),
    path('internships', views.list_internships_view, name='list_internships'),
    path('internship/create', views.internship_create_view, name='internship_create'),
    path('internship/<int:pk>', views.internship_detail_view, name='internship_detail'),
    path('internship/<int:pk>/edit', views.internship_edit_view, name='internship_edit'),
    path('internship/<int:pk>/apply', views.internship_apply_view, name='internship_apply'),
    path('internship/<int:pk>/interns', views.internship_interns_view, name='internship_interns'),
    path('intern/<int:pk>/attach', views.intern_attach_view, name='intern_attach'),
    path('intern/<int:pk>/add-review', views.internship_student_add_review_view, name='internship_student_add_review'),
    path('internship/<int:pk>/applications', views.internship_applications_view, name='internship_applications'),
    path('internship/<int:internship_pk>/application/<int:application_pk>', views.internship_application_detail_view, name='internship_application_detail'),
    path('internship/<int:internship_pk>/application/<int:application_pk>/reject', views.internship_application_reject_view, name='internship_application_reject'),
    path('internship/<int:internship_pk>/application/<int:application_pk>/approve', views.internship_application_approve_view, name='internship_application_approve'),
    path('student/account', views.student_personal_account_view, name='student_personal_account'),
    path('student/internship-application/<int:pk>', views.student_internship_application_detail, name='student_internship_application_detail'),
    path('student/edit', views.student_edit_view, name='student_edit'),
    path('student/<int:pk>', views.student_detail_view, name='student_detail'),

    path('api/student/search-skills', views.search_student_skills_view, name='search_student_skills'),
    path('api/student/education/create', views.api_student_educuation_create_view, name='api_student_educuation_create'),
    path('api/student/education/<int:pk>/edit', views.api_student_education_edit_view, name='api_student_education_edit'),
    path('api/student/education/<int:pk>/delete', views.api_student_education_delete_view, name='api_student_education_delete'),
    path('api/student/work/create', views.api_student_work_create_view, name='api_student_work_create'),
    path('api/student/work/<int:pk>/edit', views.api_student_work_edit_view, name='api_student_work_edit'),
    path('api/student/work/<int:pk>/delete', views.api_student_work_delete_view, name='api_student_work_delete'),
    path('api/student/publication/create', views.api_student_publication_create_view, name='api_student_publication_create'),
    path('api/student/publication/<int:pk>/edit', views.api_student_publication_edit_view, name='api_student_publication_edit'),
    path('api/student/publication/<int:pk>/delete', views.api_student_publication_delete_view, name='api_student_publication_delete'),
    path('api/student/skill/add', views.api_student_skill_add_view, name='api_student_skill_add'),
    path('api/student/skill/<int:pk>/remove', views.api_student_skill_remove_view, name='api_student_skill_remove'),
    path('api/student/language/add', views.api_student_language_add_view, name='student_language_add'),
    path('api/student/language/<int:pk>/remove', views.api_student_language_remove_view, name='student_language_remove'),
]