# Generated by Django 3.2 on 2021-05-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_internshipstudent_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=2048, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='university',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=2048, null=True, verbose_name='Email'),
        ),
    ]
