# Generated by Django 3.2 on 2021-05-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0004_auto_20210510_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, verbose_name='Name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
