# Generated by Django 3.2 on 2021-05-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0008_auto_20210512_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfirmation',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
