# Generated by Django 3.2 on 2021-05-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0009_userconfirmation_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmation',
            name='user_type',
            field=models.CharField(choices=[('student', 'student'), ('university', 'university'), ('university representative', 'university representative'), ('company', 'company'), ('admin', 'admin')], max_length=126, verbose_name='User Type'),
        ),
    ]
