# Generated by Django 3.2 on 2021-05-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0010_alter_userconfirmation_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmation',
            name='user_type',
            field=models.CharField(choices=[('student', 'student'), ('university', 'university'), ('company', 'company'), ('University Representative', 'University Representative'), ('Company Representative', 'Company Representative'), ('SuperAdmin', 'SuperAdmin')], max_length=126, verbose_name='User Type'),
        ),
    ]
