# Generated by Django 3.2 on 2021-05-26 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0012_userconfirmation_reseted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfirmation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='internships.company'),
        ),
        migrations.AddField(
            model_name='userconfirmation',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='internships.university'),
        ),
    ]
