# Generated by Django 3.2 on 2021-05-28 17:42

from django.db import migrations, models
import django.db.models.deletion
import internships.models
import internships.services.validators


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0014_auto_20210528_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=internships.models.get_internship_application_file_path, validators=[internships.services.validators.file_max_10mb_size], verbose_name='File')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='internships.internshipreview')),
            ],
        ),
    ]
