# Generated by Django 3.2 on 2021-05-29 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0015_internshipfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='internships.university'),
        ),
        migrations.AddField(
            model_name='student',
            name='university_email',
            field=models.EmailField(blank=True, default='', max_length=2048, null=True, verbose_name='University Email'),
        ),
    ]
