# Generated by Django 3.2 on 2021-05-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0017_student_university_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipreview',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2021-05-29 15:22'),
            preserve_default=False,
        ),
    ]
