# Generated by Django 3.2 on 2021-08-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0018_internshipreview_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='card_number',
            field=models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='StudentCardNumber'),
        ),
    ]
