# Generated by Django 3.2 on 2021-08-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0019_student_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='confirmed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Confirmed'),
        ),
    ]
