# Generated by Django 3.2 on 2021-08-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0020_student_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfirmation',
            name='card_number',
            field=models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='StudentCardNumber'),
        ),
    ]
