# Generated by Django 3.2 on 2021-08-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0021_userconfirmation_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_merit',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Academic merit'),
        ),
        migrations.AddField(
            model_name='student',
            name='language_skill',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Language skill'),
        ),
        migrations.AddField(
            model_name='student',
            name='motivation',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Motivation'),
        ),
        migrations.AddField(
            model_name='student',
            name='overall',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Overall assessment'),
        ),
        migrations.AddField(
            model_name='student',
            name='research_experience',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Research experience'),
        ),
    ]
